version: latest

services:
  auth-app:
    container_name: auth-app
    build: .
    volumes:
      - .:/app
    command: ./entrypoint.sh
    depends_on:
      - db
    env_file:
      .env
    ports:
      - 8001:8001
    networks:
      - network

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./psql/:/var/lib/postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge
    name: microservices
    external: true
