# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_/unary_auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16grpc_/unary_auth.proto\x12\x05unary\"\x1c\n\x0bRequestUser\x12\r\n\x05token\x18\x01 \x01(\t\"\x8b\x01\n\x08Response\x12\x19\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0b.unary.User\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\x12\'\n\x04meta\x18\x03 \x03(\x0b\x32\x19.unary.Response.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2F\n\x0b\x41uthService\x12\x37\n\x0eGetUserByToken\x12\x12.unary.RequestUser\x1a\x0f.unary.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_.unary_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE_METAENTRY']._loaded_options = None
  _globals['_RESPONSE_METAENTRY']._serialized_options = b'8\001'
  _globals['_REQUESTUSER']._serialized_start=33
  _globals['_REQUESTUSER']._serialized_end=61
  _globals['_RESPONSE']._serialized_start=64
  _globals['_RESPONSE']._serialized_end=203
  _globals['_RESPONSE_METAENTRY']._serialized_start=160
  _globals['_RESPONSE_METAENTRY']._serialized_end=203
  _globals['_USER']._serialized_start=205
  _globals['_USER']._serialized_end=256
  _globals['_AUTHSERVICE']._serialized_start=258
  _globals['_AUTHSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
