version: '3.8'

services:
  product-app:
    container_name: product-app
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - mongo-express
    command: uvicorn main:app_factory --factory --port 8000 --host 0.0.0.0 --reload
    networks:
      - microservices

  mongodb:
    container_name: mongo-main
    image: mongo:6-jammy
    env_file:
      .env
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/mongodb/data
    networks:
      - microservices

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 28081:8081
    env_file:
      .env
    depends_on:
      - mongodb
    networks:
      - microservices

networks:
  microservices:
    name: repo:microservices-example
    driver: bridge
